### ISSUE TITLE
General Enquiry about the project.

### ISSUE THREAD

**Issue by DisneyGaming** [Team-Lodestone/Documentation#9]
Hi,

I'm curious on this project's attempts on converting LCE psvita to a different platform. I have taken a look at the file in a hex editor and compared this to a ps3 save to show that there are many differences and a direct conversion (from a quick glance) isn't possible without a bunch of other measures, I'm more so curious on how you will/have, converted the save to a usable format. My second question is that do you guys have a discord for the public to keep in the loop with without having to come back to the github every now and again to see if there are any updates. (thats if this project is still under development, which I assume it is considering the repo updates).

Hoping to see this project come to fruition!

**Comment by EternalModz** [comment]
> Hi,
> 
> I'm curious on this project's attempts on converting LCE psvita to a different platform. I have taken a look at the file in a hex editor and compared this to a ps3 save to show that there are many differences and a direct conversion (from a quick glance) isn't possible without a bunch of other measures, I'm more so curious on how you will/have, converted the save to a usable format. My second question is that do you guys have a discord for the public to keep in the loop with without having to come back to the github every now and again to see if there are any updates. (thats if this project is still under development, which I assume it is considering the repo updates).
> 
> Hoping to see this project come to fruition!

Hi, I’ve added you on Discord. We can talk there about the project.
